### PR TITLE
Fix input value not in specified range

### LINKED ISSUE #850: Range Input: Order of Attributes Bug
I stumbled upon a bug while working with Preact today. If you create an input range, the initial render of the slider position may be wrong, depending on the order of the attributes. The `value` attribute needs to be set after `min`/`max`/`step`. If `value` is applied before `min`/`max`/`step` are properly set, the value will be forced to match the default min=0/max=100/step=1 on a slider.

E.g. if you create two sliders:

```js
// This one renders with the slider at 0
<input type="range" value={0.5} min="0" max="1" step="0.05" />

// This one renders with the slider at 0.5
<input type="range" min="0" max="1" step="0.05" value={0.5} />
```

image

See minimal code to reproduce [here](https://codepen.io/mikewesthad/pen/gxEmmx)

When creating an dom element from a vnode, it looks like attributes are applied one at a time via a `for...in` loop. Since the ordering of keys in an object is arbitrary, it seems like [`diffAttributes`](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L294) needs to apply the attributes in a sorted way. I can't think of other potential ordering pitfalls with attributes (maybe the react source code would have insights), but at the very least, applying `value` last should fix this issue.

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fixes #850 .
Adds ~~`+11`~~ ~~`+10`~~ ~~`+21`~~ `+19 B`

### CODE REVIEW

File: src/diff/props.js [hunk 1]
```diff
@@ -11,12 +11,17 @@ import options from '../options';
  */
 export function diffProps(dom, newProps, oldProps, isSvg) {
```
Comment (robertknight) [inline src/diff/props.js]: Can `newProps` or `oldProps` be null or undefined here? If so it would help to clarify that in the function signature.

File: src/diff/props.js [hunk 2]
```diff
@@ -11,12 +11,17 @@ import options from '../options';
...
 		}
 	}
+
+	// `value` needs to be applied after an input's `min`, `max` and `step`
+	// attribute are set. See preact/#850
+	if (newProps.value!=null) dom.value = newProps.value;
+
 	for (let i in oldProps) {
-		if (i!=='children' && i!=='key' && (!newProps || !(i in newProps))) {
+		if (i!=='children' && i!=='key' && !(i in newProps)) {
```
Comment (robertknight) [inline src/diff/props.js]: Is the removal of `!newProps` check because `newProps` is guaranteed to be non-null here?

File: test/browser/render.test.js [hunk 3]
```diff
@@ -241,6 +241,14 @@ describe('render()', () => {
 		expect(root.children[3]).to.have.property('value', '');
 	});
 
+	it('should set value inside the specified range', () => {
+		render(
+			<input type="range" value={0.5} min="0" max="1" step="0.05" />,
+			scratch
+		);
```
Comment (robertknight) [inline test/browser/render.test.js]: _(Note for my understanding)_ - So in this test case, if the `type` property is set to `range` and then `value` is set before `min`, `max` or `step` then `value` will be rounded to "1" because the [default values for min, max and step](https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range)) are 0, 100 and 1 respectively.

File: src/diff/props.js [hunk 4]
```diff
@@ -11,12 +11,17 @@ import options from '../options';
...
 export function diffProps(dom, newProps, oldProps, isSvg) {
 	for (let i in newProps) {
-		if (i!=='children' && i!=='key' && (!oldProps || oldProps[i]!=newProps[i])) {
+		if (i!=='children' && i!=='key' && i!=='value' && (!oldProps || oldProps[i]!=newProps[i])) {
 			setProperty(dom, i, newProps[i], oldProps[i], isSvg);
 		}
 	}
+
+	// `value` needs to be applied after an input's `min`, `max` and `step`
+	// attribute are set. See preact/#850
```
Comment (robertknight) [inline src/diff/props.js]: I wonder if there are any other dependencies here? I presume there is one between `type` and `value`, which is also covered by this change.

Comment (robertknight) [inline src/diff/props.js]: Do you mean after an input's `min`, `max` and `step` _properties_ are set?

File: src/diff/props.js (hunk 2 above)
Comment (marvinhagemeister) [reply src/diff/props.js]: yup, we always set at least an empty `object` https://github.com/developit/preact/blob/0baf368ca803e0deb6b3d7edd2e09f6bbd564505/src/create-element.js#L12

File: test/browser/render.test.js (hunk 3 above)
Comment (marvinhagemeister) [reply test/browser/render.test.js]: That's exactly what happens 👍 The browser won't update the value when the range boundaries change.

File: src/diff/props.js (hunk 4 above)
Comment (marvinhagemeister) [reply src/diff/props.js]: ohh you got me haha

Comment (marvinhagemeister) [reply src/diff/props.js]: Not sure but we didn't receive any bug reports for these so far, even during the 8.x release line. So I guess browsers deal with `type` themselves.

File: src/diff/props.js (hunk 1 above)
Comment (marvinhagemeister) [reply src/diff/props.js]: Afaik they are never `null` here. When I remove the `!oldProps` check the byte-size goes up by `+7B` 🤷‍♂️

**Comment by marvinhagemeister** [comment]
This PR also fixes the CI error on the `master` branch 👍

File: src/diff/index.js [hunk 5]
```diff
@@ -270,9 +270,9 @@ function diffElementNodes(dom, newVNode, oldVNode, context, isSvg, excessDomChil
 					dom.innerHTML = newHtml && newHtml.__html || '';
 				}
 			}
-			if (newProps.multiple) {
-				dom.multiple = newProps.multiple;
-			}
+			// Needs to be set before diffing children for <select>'s with multiple
+			// options.
+			if (newProps.multiple) dom.multiple = newProps.multiple;
```
Comment (developit) [inline src/diff/index.js]: Is this still needed with children now being diffed before props?

File: src/diff/props.js (hunk 1 above)
Comment (developit) [reply src/diff/props.js]: Any chance this would trip for a vnode that swaps from Text to Element?

```
render(<div>foo</div>, root)
render(<div><span a /></div>, root)
```

**Comment by developit** [comment]
So one weird thing about this is that the issue only shows up when the `value` isn't specified last. At the time #850 was filed I'd wondered if this would be easier to implement via Object.keys.

File: src/diff/index.js (hunk 5 above)
Comment (marvinhagemeister) [reply src/diff/index.js]: Unfortunately not. This issue is caused when the value is set before the range boundaries are applied. At the time when value is set, the browser will default to the fallback range of 0-100 and won't update `value` when `min/max/step` are added later.

Comment (marvinhagemeister) [reply src/diff/index.js]: yeah the multiple property must be set before `children` are diffed, otherwise there will be only one `<option>` with a selected value. That's the only exception we've found so far :/

File: src/diff/props.js (hunk 1 above)
Comment (marvinhagemeister) [reply src/diff/props.js]: Good call, we need to keep that check :+1:

**Comment by marvinhagemeister** [comment]
Went with the `Object.keys()` route as @developit suggested. Added back the `!newProps` null check and with it even the previous solution would be the same in term of byte size.
